Traceback (most recent call last):
  File "/Users/sah2249/miniconda3/envs/stat-methods-course/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/sah2249/miniconda3/envs/stat-methods-course/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sah2249/miniconda3/envs/stat-methods-course/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sah2249/miniconda3/envs/stat-methods-course/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/sah2249/miniconda3/envs/stat-methods-course/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/sah2249/miniconda3/envs/stat-methods-course/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/sah2249/miniconda3/envs/stat-methods-course/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
The variance
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mSyntaxError[0m                               Traceback (most recent call last)
File [0;32m~/miniconda3/envs/stat-methods-course/lib/python3.11/site-packages/IPython/core/compilerop.py:86[0m, in [0;36mCachingCompiler.ast_parse[0;34m(self, source, filename, symbol)[0m
[1;32m     81[0m [38;5;28;01mdef[39;00m [38;5;21mast_parse[39m([38;5;28mself[39m, source, filename[38;5;241m=[39m[38;5;124m'[39m[38;5;124m<unknown>[39m[38;5;124m'[39m, symbol[38;5;241m=[39m[38;5;124m'[39m[38;5;124mexec[39m[38;5;124m'[39m):
[1;32m     82[0m [38;5;250m    [39m[38;5;124;03m"""Parse code to an AST with the current compiler flags active.[39;00m
[1;32m     83[0m 
[1;32m     84[0m [38;5;124;03m    Arguments are exactly the same as ast.parse (in the standard library),[39;00m
[1;32m     85[0m [38;5;124;03m    and are passed to the built-in compile function."""[39;00m
[0;32m---> 86[0m     [38;5;28;01mreturn[39;00m [38;5;28mcompile[39m(source, filename, symbol, [38;5;28mself[39m[38;5;241m.[39mflags [38;5;241m|[39m PyCF_ONLY_AST, [38;5;241m1[39m)

[0;31mSyntaxError[0m: invalid syntax (2322155707.py, line 1)

